# Generated by Django 5.0.6 on 2024-06-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='modelo',
        ),
    ]
