# Generated by Django 5.0.6 on 2024-07-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miappservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='titulo',
            new_name='title',
        ),
    ]
