# Generated by Django 5.0.6 on 2024-07-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miappservices', '0004_alter_services_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
    ]
